local env = select(2, ...)
local UICCommonButton = env.AX_Modules:Import("ax_modules\\uic-common\\button")
local UICCommonCheckButton = env.AX_Modules:Import("ax_modules\\uic-common\\check-button")
local UICCommonRange = env.AX_Modules:Import("ax_modules\\uic-common\\range")
local UICCommonScrollBar = env.AX_Modules:Import("ax_modules\\uic-common\\scroll-bar")
local UICCommonInput = env.AX_Modules:Import("ax_modules\\uic-common\\input")
local UICCommonSelectionMenu = env.AX_Modules:Import("ax_modules\\uic-common\\selection-menu")
local UICCommonColorInput = env.AX_Modules:Import("ax_modules\\uic-common\\color-input")
local UICCommonPrompt = env.AX_Modules:Import("ax_modules\\uic-common\\prompt")
local UICCommon = env.AX_Modules:New("ax_modules\\uic-common")

UICCommon.ButtonRed = UICCommonButton.RedBase
UICCommon.ButtonGray = UICCommonButton.GrayBase
UICCommon.ButtonRedSquare = UICCommonButton.RedBaseSquare
UICCommon.ButtonGraySquare = UICCommonButton.GrayBaseSquare
UICCommon.ButtonRedWithText = UICCommonButton.RedWithText
UICCommon.ButtonGrayWithText = UICCommonButton.GrayWithText
UICCommon.ButtonRedClose = UICCommonButton.RedClose
UICCommon.ButtonSelectionMenu = UICCommonButton.SelectionMenu
UICCommon.CheckButton = UICCommonCheckButton.New
UICCommon.ScrollBar = UICCommonScrollBar.New
UICCommon.Input = UICCommonInput.New
UICCommon.InputUIDef = UICCommonInput.UIDef
UICCommon.Range = UICCommonRange.New
UICCommon.RangeWithText = UICCommonRange.NewWithText
UICCommon.SelectionMenu = UICCommonSelectionMenu.New
UICCommon.ColorInput = UICCommonColorInput.New
UICCommon.Prompt = UICCommonPrompt.New
